platform :ios, '14.0'

target 'App' do
  use_frameworks!
  
  # RevenueCat
  pod 'RevenueCat', '~> 5.0'
  pod 'RevenueCatUI', '~> 5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
